# 🚀 DEPLOYMENT SCRIPT - AILUN SAÚDE
# Executar deployment no Vercel via navegador

echo "🚀 INICIANDO DEPLOYMENT COMPLETO"
echo "================================"
echo ""
echo "📋 INSTRUÇÕES PARA DEPLOYMENT VIA NAVEGADOR:"
echo ""
echo "1. ABRA O NAVEGADOR E ACESSE:"
echo "   https://vercel.com/dashboard"
echo ""
echo "2. CLIQUE EM 'NEW PROJECT'"
echo ""
echo "3. ESCOLHA 'UPLOAD' E SELECIONE TODOS OS ARQUIVOS:"
ls -la *.html *.json assets/* api/*
echo ""
echo "4. CONFIGURE AS VARIÁVEIS DE AMBIENTE:"
echo "   RAPIDOC_BASE_URL=https://api.rapidoc.tech"
echo "   RAPIDOC_CLIENT_ID=540e4b44-d68d-4ade-885f-fd4940a3a045"
echo "   RAPIDOC_TOKEN=eyJhbGciOiJSUzUxMiJ9.eyJjbGllbnQiOiJBSUxVTiBURUNOT0xPR0lBIn0.Wkzl4kZkBhTCHoSI_9r5TDmTY9ZHrxIj7kyCUvWeXM9FKIhpf9vY464wFwb4u0K_ys_TtB00awXU42duDxEz_KJ4oloJbklLsIaiHW6OgGnrv5iLN1wNYb9uTPDJjCkiNBtNIr0F5_7U8gV6qwztAWn5vY8qrt7DxOoaO_8uIe-jydSZYjl9jMtMjWd3phmjjxfoDLqLGRKoSgw01Efk6ivkzndB2gcdmZIz6tgwhTfwuQLRkhMmqCv188twAkP2Dyt8A_OREr8iyiXHlBNlZnLcYlng5_9PHDUww2exl_QC6RuhB2k-vwsZ4eOxjOThpkCWT-E4zomUMpVuoEFtN_yt3vGiTwr_WHWjleDnOR1CeGCtxRCDmzU7IGmwa7fEhOrx7VUXPKZKidmF2HGicBq4QK22JvAimuDstuAcHIepr9gs8abm0p93_-BbnZDoM4edmhFLvBykfbV-rXVhen0nJVm5c9av4QP8tb41lglrs3DVa7KCqESG8kB47uCf74K8GJLpHzgk2ERHH_E3o1I_NdFwf1qZTAxiCCGIi0wjtVkU9zTrEyNb5HNpSgXn3Hj7IyMiCvHTzrweY7aizFF9uyrIf_5-SY-jmE-XuhvZiOuRQO-7XnCWHtuuuHXUVxKEFmG7EQWvI-e7z62cAJdQZhlxEBtepSgzpC_GKPc"
echo "   COOKIE_SECURE=true"
echo "   NODE_ENV=production"
echo ""
echo "5. CLIQUE EM 'DEPLOY'"
echo ""
echo "6. AGUARDE 2-3 MINUTOS"
echo ""
echo "🎯 URL FINAL: https://ailun-saude.vercel.app"
echo ""
echo "🔄 APÓS O DEPLOY, TESTE:"
echo "   - Login com suas credenciais"
echo "   - Cadastro de beneficiário"
echo "   - Agendamento de consulta"
echo ""
echo "📞 EM CASO DE ERRO, VERIFIQUE:"
echo "   - Logs no painel do Vercel"
echo "   - Variáveis de ambiente"
echo "   - Conexão com API Rapidoc"
echo ""
echo "✅ BOA SORTE COM O DEPLOY! 🚀"